# -*- coding: utf-8 -*-
"""python_basics<Naveen_Eslavath>.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Z4g-LRVTde71nMCwkNagBdncvZ4VDAL
"""

name = "Naveen"
age = 27
height = 5.4
is_student = True
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")
age_in_months = age*12
age_in_days = age*365
reminder_age_devided_seven = age%7
age_raised = age**2
print("Age in months:", age_in_months)
print("Age in days:", age_in_days)
print("Reminder age devided by 7:", reminder_age_devided_seven)
print("Age raised to the power of 2:", age_raised)











